import { io } from 'socket.io-client';
const PRODUCTION_API=import.meta.env.VITE_PRODUCTION_API_URL || 'https://photocall-backend.vercel.app';
const configuredApi=import.meta.env.VITE_API_URL;
const configuredSocket=import.meta.env.VITE_SOCKET_URL;
const isProductionHost=window.location.hostname==='photocall-frontend.vercel.app';
const API=(isProductionHost ? PRODUCTION_API : (configuredApi || PRODUCTION_API)).replace(/\/$/,'');
const SOCKET_URL=(isProductionHost ? PRODUCTION_API : (configuredSocket || API)).replace(/\/$/,'');
const socket=io(SOCKET_URL,{auth:{token:localStorage.getItem('photocall_token')},transports:['websocket','polling'],autoConnect:false});
const room=document.querySelector('#room'),join=document.querySelector('#join'),leave=document.querySelector('#leave'),shareSignal=document.querySelector('#shareSignal'),video=document.querySelector('#remote'),state=document.querySelector('#state'),status=document.querySelector('#status');
let pc=null,joined=false,iceServers=[{urls:['stun:stun.l.google.com:19302']}];
async function config(){try{const r=await fetch(API+'/api/config');if(r.ok){const data=await r.json();iceServers=data.iceServers||iceServers}}catch(e){console.error('TURN configuration unavailable',e)}}
config();
const params=new URLSearchParams(location.search); if(params.get('room')) room.value=params.get('room').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);
function make(){pc=new RTCPeerConnection({iceServers});pc.ontrack=e=>{video.srcObject=e.streams[0];state.textContent='Connected — live avatar + processed voice';video.play().catch(()=>{})};pc.onicecandidate=e=>e.candidate&&socket.emit('ice-candidate',{room:room.value.trim(),candidate:e.candidate});pc.onconnectionstatechange=()=>{if(!pc)return;state.textContent=`Connection: ${pc.connectionState}`;if(['failed','closed'].includes(pc.connectionState))cleanup(false)};pc.oniceconnectionstatechange=()=>{if(pc?.iceConnectionState==='failed')state.textContent='ICE connection failed. Check TURN configuration.'}}
join.onclick=()=>{if(!localStorage.getItem('photocall_token'))return state.textContent='Sign in on the main PhotoCall page first.';if(!socket.connected)socket.connect();const r=room.value.trim();if(!r)return state.textContent='Enter a room code.';make();socket.emit('join-room',r);joined=true;join.disabled=true;leave.disabled=false;room.disabled=true;state.textContent='Joined. Waiting for caller…'};
socket.on('offer',async d=>{if(!pc)make();await pc.setRemoteDescription(d.offer);const a=await pc.createAnswer();await pc.setLocalDescription(a);socket.emit('answer',{room:room.value.trim(),answer:pc.localDescription})});
socket.on('ice-candidate',d=>pc?.addIceCandidate(d.candidate).catch(()=>{}));socket.on('call-ended',()=>{state.textContent='Caller ended the call.';cleanup(false)});socket.on('peer-left',()=>{state.textContent='Caller left the room.';cleanup(false)});socket.on('room-full',()=>{state.textContent='Room is full.';cleanup(false)});socket.on('server-error',d=>state.textContent=d.message||'Server error.');socket.on('connect',()=>{status.textContent='Signaling online';status.className='status online'});socket.on('connect_error',e=>{status.textContent='Signaling error';status.className='status offline';state.textContent=e.message});socket.on('disconnect',()=>{status.textContent='Signaling offline';status.className='status offline'});
shareSignal.onclick=async()=>{const url=new URL('/receiver.html?room='+encodeURIComponent(room.value.trim()),location.href).href;const text=`Join my PhotoCall call: ${url}\nRoom: ${room.value.trim()}`;try{if(navigator.share){await navigator.share({title:'PhotoCall call',text});state.textContent='Invite ready to share. Select Signal if it is available.'}else{await navigator.clipboard.writeText(text);state.textContent='Invite copied. Open Signal and paste it into your chat.'}}catch(e){if(e.name!=='AbortError')state.textContent='Unable to open sharing.'}};
function cleanup(emit){if(emit&&joined)socket.emit('leave-room');pc?.close();pc=null;joined=false;video.srcObject=null;join.disabled=false;leave.disabled=true;room.disabled=false}leave.onclick=()=>cleanup(true);
