const candidates=[import.meta.env.VITE_API_URL,import.meta.env.VITE_PRODUCTION_API_URL,'https://photocall-backend.vercel.app'].filter(Boolean).map(v=>String(v).replace(/\/$/,''));
let API=candidates[0]||'',guestId=localStorage.getItem('photocall_guest_id')||crypto.randomUUID(),pollTimer=null,lastEventId='000000000000000000000000',pc=null,joined=false,iceServers=[{urls:['stun:stun.l.google.com:19302']}];
localStorage.setItem('photocall_guest_id',guestId);
const room=document.querySelector('#room'),join=document.querySelector('#join'),leave=document.querySelector('#leave'),shareSignal=document.querySelector('#shareSignal'),video=document.querySelector('#remote'),state=document.querySelector('#state'),status=document.querySelector('#status');
const params=new URLSearchParams(location.search); if(params.get('room')) room.value=params.get('room').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);
async function req(path,options={}){const r=await fetch(API+path,{...options,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
async function discover(){for(const base of [...new Set(candidates)]){try{const r=await fetch(base+'/health');if(r.ok){API=base;return true}}catch{}}return false}
async function config(){if(!API)await discover();if(!API)throw new Error('Backend unavailable');const d=await req('/api/config');iceServers=d.iceServers||iceServers;await req('/api/session/guest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({guestId})})}
async function signal(type,payload={}){return req(`/api/rooms/${encodeURIComponent(room.value.trim())}/events`,{method:'POST',headers:{'Content-Type':'application/json','X-Guest-Id':guestId},body:JSON.stringify({type,payload})})}
async function poll(){if(!joined)return;try{const d=await req(`/api/rooms/${encodeURIComponent(room.value.trim())}/events?after=${encodeURIComponent(lastEventId)}`,{headers:{'X-Guest-Id':guestId}});for(const e of d.events||[]){lastEventId=e.id;await handle(e)}}catch(e){console.warn(e)}}
function startPoll(){clearInterval(pollTimer);pollTimer=setInterval(poll,800);poll()}
async function handle(e){if(e.type==='offer'){if(!pc)make();await pc.setRemoteDescription(e.payload.offer);const a=await pc.createAnswer();await pc.setLocalDescription(a);await signal('answer',{answer:pc.localDescription});state.textContent='Connecting…'}else if(e.type==='ice-candidate'){if(pc&&e.payload?.candidate)await pc.addIceCandidate(e.payload.candidate).catch(()=>{})}else if(e.type==='call-ended'||e.type==='leave'){state.textContent='Caller ended the call.';cleanup(false)}}
function make(){pc=new RTCPeerConnection({iceServers});pc.ontrack=e=>{video.srcObject=e.streams[0];state.textContent='Connected — live PhotoCall avatar';video.play().catch(()=>{})};pc.onicecandidate=e=>e.candidate&&signal('ice-candidate',{candidate:e.candidate});pc.onconnectionstatechange=()=>{if(!pc)return;state.textContent=`Connection: ${pc.connectionState}`;if(['failed','closed'].includes(pc.connectionState))cleanup(false)}}
join.onclick=async()=>{try{if(!API)await discover();await config();const r=room.value.trim();if(!r)return state.textContent='Enter a room code.';await req('/api/rooms/join',{method:'POST',headers:{'Content-Type':'application/json','X-Guest-Id':guestId},body:JSON.stringify({room:r,guestId})});make();joined=true;lastEventId='000000000000000000000000';join.disabled=true;leave.disabled=false;room.disabled=true;status.textContent='Signaling online';status.className='status online';state.textContent='Joined. Waiting for caller…';startPoll()}catch(e){state.textContent=e.message||'Unable to join.';status.textContent='Offline';status.className='status offline'}};
shareSignal.onclick=async()=>{const url=new URL('/receiver.html?room='+encodeURIComponent(room.value.trim()),location.href).href;const text=`Join my PhotoCall call: ${url}\nRoom: ${room.value.trim()}`;try{if(navigator.share){await navigator.share({title:'PhotoCall call',text});state.textContent='Share opened. Choose Signal.'}else{await navigator.clipboard.writeText(text);state.textContent='Invite copied.'}}catch(e){if(e.name!=='AbortError')state.textContent='Unable to open sharing.'}};
async function cleanup(emit){if(emit&&joined)try{await signal('leave')}catch{}clearInterval(pollTimer);pollTimer=null;pc?.close();pc=null;joined=false;video.srcObject=null;join.disabled=false;leave.disabled=true;room.disabled=false}leave.onclick=()=>cleanup(true);
config().catch(()=>{});
